#!/usr/bin/env python3.11
"""Consolidated hyperparameter table, generated from the training configs.

Reads the two flagship run configs (one per channel), merges their local
`defaults` chains (plain YAML deep-merge; verl's ppo_trainer base is
upstream and not needed for the reported keys), pulls each reported value
by path, and emits generated/tables/hyperparams.tex. A missing key raises,
so the table cannot silently drift from the configs.

    /usr/bin/python3.11 scripts/analysis/hyperparam_table.py \\
        --grpo qwen3_8b_grpo_pd_deon_tft_200 \\
        --sdpo qwen3_8b_sdpo_pd_deon-repair-gen_tft_200
"""
from __future__ import annotations

import argparse
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[2]
TRAIN = ROOT / "configs" / "training"
DATA = ROOT / "configs" / "datasets"


def merge(base: dict, over: dict) -> dict:
    out = dict(base)
    for k, v in over.items():
        out[k] = merge(out[k], v) if (
            isinstance(v, dict) and isinstance(out.get(k), dict)) else v
    return out


def load(name: str) -> dict:
    cfg = yaml.safe_load(open(TRAIN / f"{name}.yaml"))
    merged: dict = {}
    for d in cfg.pop("defaults", []):
        if d == "_self_" or not (TRAIN / f"{d}.yaml").exists():
            continue
        merged = merge(merged, load(d))
    return merge(merged, cfg)


def get(cfg: dict, path: str):
    cur = cfg
    for part in path.split("."):
        cur = cur[part]
    return cur


def sci(x) -> str:
    return f"${float(x):.1e}".replace("e-0", r"\times10^{-") + "}$"


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--grpo", required=True)
    ap.add_argument("--sdpo", required=True)
    ap.add_argument("--out", type=Path, default=Path(
        "eval_results/post_training/comparison/analysis"))
    args = ap.parse_args()
    G, S = load(args.grpo), load(args.sdpo)
    dg = yaml.safe_load(open(DATA / "grpo_pd_deon_tft.yaml"))["reward"]
    ds = yaml.safe_load(open(DATA / "sdpo_pd_deon-repair-gen_tft.yaml"))["reward"]
    A = "actor_rollout_ref."

    def both(path, fmt=str):
        g, s = get(G, path), get(S, path)
        assert g == s, f"{path} differs ({g} vs {s}) -- move it to a channel row"
        return fmt(g)

    shared = [
        ("LoRA rank $r$ / $\\alpha$",
         f"{both(A+'model.lora_rank')} / {both(A+'model.lora_alpha')}"),
        ("LoRA target modules", both(A + "model.target_modules")),
        ("Prompt / response budget (tokens)",
         f"{both('data.max_prompt_length')} / {both('data.max_response_length')}"),
        ("Prompts per step $\\times$ rollouts (GRPO group)",
         f"{both('data.train_batch_size')} $\\times$ {both(A+'rollout.n')}"),
        ("Sampling $T$ / top-$p$",
         f"{both(A+'rollout.temperature')} / {both(A+'rollout.top_p')}"),
        ("Optimizer", "AdamW"),
        ("Checkpoint / validation interval (steps)",
         f"{both('trainer.save_freq')} / {both('trainer.test_freq')}"),
        ("Hardware per run", "1 node $\\times$ 4 GH200"),
    ]
    assert dg["intrinsic"] == "deontological" and ds["intrinsic"] == "none"
    channel = [
        ("Policy loss", get(G, A + "actor.policy_loss.loss_mode"),
         get(S, A + "actor.policy_loss.loss_mode") + " (replaces PG)"),
        ("Reward in the gradient",
         f"normalized game $+\\,{dg['lambda']}\\cdot$deon penalty",
         "none (intrinsic none, $\\lambda{=}0$)"),
        ("Moral signal carrier", "scalar reward",
         f"principle text in teacher context"),
        ("KL / teacher anchor",
         f"KL to reference, $\\beta{{=}}{get(G, A+'actor.kl_loss_coef')}$",
         f"EMA teacher, rate {get(S, A+'actor.self_distillation.teacher_update_rate')}"),
        ("Distillation", "none",
         f"JSD $\\alpha{{=}}{get(S, A+'actor.self_distillation.alpha')}$, "
         f"top-{get(S, A+'actor.self_distillation.distillation_topk')}"
         f"{'+tail' if get(S, A+'actor.self_distillation.distillation_add_tail') else ''} logits"),
        ("Learning rate / warmup steps",
         f"{sci(get(G, A+'actor.optim.lr'))} / {get(G, A+'actor.optim.lr_warmup_steps')}",
         f"{sci(get(S, A+'actor.optim.lr'))} / {get(S, A+'actor.optim.lr_warmup_steps')}"),
        ("Training steps", str(get(G, "trainer.total_training_steps")),
         str(get(S, "trainer.total_training_steps"))),
    ]
    lines = [
        "% Generated by scripts/analysis/hyperparam_table.py -- do not edit.",
        "\\begin{table}[H]", "\\centering",
        "\\caption{Training configuration, extracted from the flagship run",
        f"configs (\\texttt{{{args.grpo.replace('_', '_')}}} /".replace("_", "\\_"),
        f"\\texttt{{{args.sdpo}}}).".replace("_", "\\_"),
        "The upper block is shared by both algorithms; the lower block is",
        "where the algorithms differ by design. Replication runs change only",
        "the base model (and its memory accommodations); the GRPO",
        "utilitarian control changes only the reward.}",
        "\\label{tab:hyperparams}",
        "{\\small\\begin{tabular}{lll}", "\\toprule",
        "Parameter & GRPO & SDPO \\\\", "\\midrule",
    ]
    for label, v in shared:
        lines.append(f"{label} & \\multicolumn{{2}}{{c}}{{{v}}} \\\\")
    lines.append("\\midrule")
    for label, g, s in channel:
        lines.append(f"{label} & {g} & {s} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}}", "\\end{table}"]
    out = args.out / "generated" / "tables" / "hyperparams.tex"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines) + "\n")
    print(f"saved -> {out}")


if __name__ == "__main__":
    main()
