#!/usr/bin/env python3.11
"""Appendix run ledger: one row per training run the report uses.

Everything is derived, not typed: the SLURM job id and (legacy) run name
come from the training log filename in ~/logs_verl/training/, wall time
from sacct, the W&B id from the log text, and model/algorithm/steps from
the canonical run name (docs/naming.md). Output is a booktabs table the
report inputs, so the ledger cannot drift from the runs.

    /usr/bin/python3.11 scripts/analysis/run_ledger.py \\
        --run qwen3_8b_grpo_pd_deon_tft_200 ... \\
        [--out eval_results/post_training/comparison/analysis]
"""
from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from specs.multi_round import LEGACY_RUNS  # noqa: E402

LOG_DIR = Path.home() / "logs_verl" / "training"
CANONICAL = {legacy: canon for legacy, canon in LEGACY_RUNS.items()}
ALGO_TEX = {"grpo": "GRPO", "sdpo": "SDPO"}


def find_log(run: str):
    """(job id, log path) for a canonical run name, via the training log
    filename <job>_<run or legacy run>.log."""
    legacy = [l for l, c in CANONICAL.items() if c == run]
    for path in sorted(LOG_DIR.glob("*.log")):
        m = re.match(r"(\d+)_(.+)\.log$", path.name)
        if m and (m.group(2) == run or m.group(2) in legacy):
            return m.group(1), path
    raise SystemExit(f"no training log for {run} under {LOG_DIR}")


def wall_time(job: str) -> str:
    try:
        out = subprocess.run(
            ["sacct", "-j", job, "-X", "-n", "-o", "Elapsed"],
            capture_output=True, text=True, timeout=30).stdout.strip()
        return out.split()[0] if out else "--"
    except Exception:
        return "--"


def wandb_id(path: Path) -> str:
    """The run URL is printed by the wandb client on stderr; check both."""
    for f in (path, path.with_suffix(".err")):
        if not f.exists():
            continue
        m = re.search(r"wandb\.ai/[^/\s]+/[^/\s]+/runs/(\w+)",
                      f.read_text(errors="replace"))
        if m:
            return m.group(1)
    return "--"


def row(run: str) -> str:
    job, log = find_log(run)
    f = run.split("_")
    model = f"{f[0]} ({f[1].upper()})"
    algo = ALGO_TEX.get(f[2], f[2])
    arm = f[4]
    steps = f[-1]
    esc_run = run.replace("_", "\\_")
    esc_arm = arm.replace("_", "\\_")
    return (f"\\texttt{{\\scriptsize {esc_run}}} & {algo} & {esc_arm} & "
            f"{steps} & {job} & {wall_time(job)} & "
            f"\\texttt{{{wandb_id(log)}}} \\\\")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--run", action="append", required=True,
                    help="canonical training run name (repeatable)")
    ap.add_argument("--out", type=Path, default=Path(
        "eval_results/post_training/comparison/analysis"))
    args = ap.parse_args()
    lines = [
        "% Generated by scripts/analysis/run_ledger.py -- do not edit.",
        "\\begin{table}[H]", "\\centering",
        "\\caption{Training-run ledger. Every run is reproducible from its",
        "name alone: \\texttt{bash scripts/slurm/train\\_verl.sh <run name>}",
        "derives the dataset (arm) configuration from the name fields and",
        "regenerates the training data bit-identically from the recorded",
        "seed; checkpoints every 10 steps are archived on tape-backed",
        "storage. Wall time is the SLURM elapsed time on one 4$\\times$GH200",
        "node.}",
        "\\label{tab:run-ledger}",
        "{\\small\\begin{tabular}{lllrrrl}", "\\toprule",
        "run & algo & arm & steps & job & wall & W\\&B \\\\",
        "\\midrule",
    ]
    lines += [row(r) for r in args.run]
    lines += ["\\bottomrule", "\\end{tabular}}", "\\end{table}"]
    out = args.out / "generated" / "tables" / "run_ledger.tex"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines) + "\n")
    print(f"saved -> {out}")


if __name__ == "__main__":
    main()
