#!/usr/bin/env python3.11
"""Reasoning-trace length table for the results report.

Mean words per reasoning trace in the PD checkpoint evaluations, per run
and checkpoint, plus a split of each run's final checkpoint into traces
that recite the teacher principle and traces that do not. Recitation uses
the same definition as the trace-language table (measures.principle_overlap,
>= OVERLAP_WORDS consecutive words verbatim), so the two tables agree.

  python3.11 scripts/analysis/trace_length_table.py \
      --ladder "Qwen3-8B GRPO=eval_results/post_training/<run>/classic/ckpt_ladder" \
      --base "Qwen3-8B GRPO=eval_results/teacher_signal/qwen3_8b/classic/single_turn_screen/cells/<base cell>" \
      [--steps 60,90,120] [--out eval_results/post_training/comparison/analysis]
"""
from __future__ import annotations

import argparse
import statistics
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "src"))
from eval_cells import load_cell  # noqa: E402
from measures import OVERLAP_WORDS, principle_ngrams, principle_overlap, words  # noqa: E402
from trace_measures import from_cells  # noqa: E402
from moralgym_verl.game.moral_values import get_moral_value  # noqa: E402


def mean_words(texts):
    return round(statistics.mean(len(words(t)) for t in texts)) if texts else None


def fmt(x):
    return "--" if x is None else str(x)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--ladder", action="append", required=True, help="label=ckpt_ladder dir")
    ap.add_argument("--base", action="append", default=[], help="label=untrained base cell dir")
    ap.add_argument("--teacher", action="append", default=[],
                    help="label=base cell with the principle in context (the initial teacher)")
    ap.add_argument("--steps", default="60,90,120")
    ap.add_argument("--principle", default="deontological+repair+generosity")
    ap.add_argument("--out", type=Path,
                    default=Path("eval_results/post_training/comparison/analysis"))
    args = ap.parse_args()
    steps = [int(s) for s in args.steps.split(",")]
    grams = principle_ngrams(get_moral_value(args.principle))
    bases = dict(b.split("=", 1) for b in args.base)
    teachers = dict(t.split("=", 1) for t in args.teacher)

    def cell_words(path):
        cell = load_cell(Path(path)) if path else None
        return mean_words([dec.trace for dec in cell.decisions]) if cell else None

    rows = []
    for spec in args.ladder:
        label, d = spec.split("=", 1)
        traces = from_cells(Path(d))
        by_step = {}
        for t in traces:
            by_step.setdefault(t.step, []).append(t.text)
        base = cell_words(bases.get(label))
        teacher = cell_words(teachers.get(label))
        final = max(by_step)
        ft = by_step[final]
        rec = [t for t in ft if principle_overlap(t, grams)]
        non = [t for t in ft if not principle_overlap(t, grams)]
        rows.append([label, fmt(base), fmt(teacher)] + [fmt(mean_words(by_step.get(s, []))) for s in steps]
                    + [f"{fmt(mean_words(ft))} ({final})", fmt(mean_words(rec)), fmt(mean_words(non)),
                       str(round(100 * len(rec) / len(ft)))])
        print(label, rows[-1][1:])

    head = " & ".join(["Run", "base", "teacher"] + [str(s) for s in steps]
                      + ["final (step)", "reciting", "not reciting", r"recites (\%)"])
    lines = [
        "% Generated by scripts/analysis/trace_length_table.py -- do not edit.",
        r"\begin{table}[H]", r"\centering",
        r"\caption{Mean words per reasoning trace in the PD checkpoint "
        r"evaluations, 400 traces per checkpoint. \\emph{Teacher} is the untrained "
        r"model with the principle in context, the initial SDPO teacher. The last three columns split "
        r"each run's final checkpoint into traces that quote at least "
        f"{OVERLAP_WORDS} consecutive words of the teacher principle and traces "
        r"that do not, with the same recitation test as "
        r"Table~\ref{tab:trace-language-pd}.}",
        r"\label{tab:trace-length}",
        r"{\small\begin{tabular}{l" + "r" * (len(steps) + 6) + "}", r"\toprule",
        head + r" \\", r"\midrule",
    ] + [" & ".join(r) + r" \\" for r in rows] + [r"\bottomrule", r"\end{tabular}}", r"\end{table}"]
    out = args.out / "generated" / "tables" / "trace_length.tex"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines) + "\n")
    print(f"saved -> {out}")


if __name__ == "__main__":
    main()
